title: project
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: author
        field:
          type: users
          display: Author
          default: current
          localizable: true
          max_items: 1
      -
        handle: template
        field:
          type: template
          display: Template
          localizable: true
      -
        handle: project_small_content
        field:
          antlers: false
          display: 'project small content'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
      -
        handle: project_content
        field:
          antlers: false
          display: 'project content'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
      -
        handle: project_image_1
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'project image 1'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          max_files: 1
      -
        handle: project_image_2
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'project image 2'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          max_files: 1
      -
        handle: project_image_3
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'project image 3'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          max_files: 1
      -
        handle: project_image_4
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'project image 4'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          max_files: 1
      -
        handle: tags
        field:
          type: terms
          taxonomies:
            - tags
          display: tags
          mode: default
          create: true
          icon: taxonomy
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: project_date
        field:
          mode: single
          time_enabled: false
          time_seconds_enabled: false
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: date
          type: date
          icon: date
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: app_link
        field:
          display: 'app link'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: git_link
        field:
          display: 'git link'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: design_link
        field:
          display: 'Design link'
          type: link
          icon: link
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
